Sts v2
Cloud-Foundations/cloud-gate pull request #45
Opened 2022-05-13 21:00 UTC by cviecco

Moving cloudfate to use sts v2

2022-05-13 21:48 UTC, kyleip approved these changes
LGTM

2022-05-17 00:22 UTC, rgooch requested changes

2022-05-17 00:22 UTC, rgooch commented on broker/aws/impl.go
> +		return nil
Does STS definitely require a Region to be specified?

2022-05-17 00:22 UTC, rgooch commented on broker/aws/impl.go
> -	b.logger.Printf("Created credentials object for static profile: %s\n",
Why remove this logging? It's useful.

2022-05-17 00:22 UTC, rgooch commented on broker/aws/impl.go
> -	b.logger.Println("Created credentials object from metadata")
Why remove this logging? It's useful.

2022-05-17 00:22 UTC, rgooch commented on broker/aws/impl.go
> +	b.logger.Debugf(1, "withAWSCredentialsProviderGetAWSRoleList: after semapore adquired")
s/adquired/acquired/

2022-05-17 00:22 UTC, rgooch commented on broker/aws/impl.go
> +		b.logger.Debugf(1, "withAWSCredentialsProviderGetAWSRoleList: fail to create new config err=%s", err)
s/fail/failed/

2022-05-17 00:22 UTC, rgooch commented on broker/aws/impl.go
> +				b.logger.Debugf(1, "withAWSCredentialsProviderGetAWSRoleList: faled to get roles, account=%s err=%s", accountName, err)
s/faled/failed/

2022-05-23 17:25 UTC, rgooch approved these changes

2022-05-24 22:38 UTC, merged